apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: htmldeployment
  name: htmldeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: htmldeployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: htmldeployment
    spec:
      containers:
      - image: htmldeployment
        name: webtest
        imagePullPolicy: Always

