apiVersion: v1
kind: Service
metadata:
  name: htmldeployment
  labels:
    app: htmldeployment
spec:
  type: NodePort
  selector:
    app: htmldeployment  # Must match the pod's label
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP

~

